runtime: nodejs18

env_variables:
  DB_HOST: "8.140.16.53"
  DB_USER: "masheng"
  DB_PASS: "masheng86"
  DB_NAME: "db"
  PORT: "8080"

handlers:
  - url: /api/.*
    script: auto
  - url: /.*
    static_files: dist/index.html
    upload: dist/index.html
  - url: /
    static_files: dist/index.html
    upload: dist/index.html